
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW, //上1下0
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//


// add module here
/*adder_8bit adder1(
	.a(SW[7:0]),
	.b(SW[7:0]),
	.s(LED[7:0])
);


/*ssd ssd1(
  .a   (SW[3:0]),
  .seg (HEX0)
);*/


fourSAS fourSAS1(
	.a(SW[3:0]),
	.b(SW[7:4]),
	.m(SW[8]),
	.seg(HEX0),
	.c(LED[0]),
	.v(LED[1])
);



//*******************************//

endmodule