
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//

// add module here
/*adder_8bit adder1(
	.a(SW[7:0]),
	.b(SW[7:0]),
	.s(LED[7:0])
);

sub_8bit sub1(
	.a(8'd20),
	.b(8'd12),
	.s()
);*/

logic clk;
logic [3:0] sec_units, min_units;
logic [2:0] sec_tens, min_tens;

freg_div_23 freg1(
	.clk(CLK),
	.reset(~BTN[0]),
	.clk_out(clk)
);

timer timer1(
	.clk(clk),
	.reset(~BTN[0]),
	.sec_units(sec_units),
	.sec_tens(sec_tens),
	.min_units(min_units),
	.min_tens(min_tens),
);

//bouns
/*day_timer timer2(
	.clk(clk),
	.reset(~BTN[0]),
	.sec_units(sec_units),
	.sec_tens(sec_tens),
	.min_units(min_units),
	.min_tens(min_tens),
);*/

ssd ssd1(
	.a(sec_units),
	.seg(HEX0)
);

ssd ssd2(
	.a(sec_tens),
	.seg(HEX1)
);

ssd ssd3(
	.a(min_units),
	.seg(HEX2)
);

ssd ssd4(
	.a(min_tens),
	.seg(HEX3)
);


//*******************************//

endmodule
