<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>sharelock_desktop</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>sharelock.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AntdUI" Version="2.2.6" />
    <PackageReference Include="Fido2" Version="4.0.0" />
    <PackageReference Include="Fido2.Models" Version="4.0.0" />
    <PackageReference Include="FirebaseAdmin" Version="3.4.0" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3240.44" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sharelock.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>