import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CircleUserRoundIcon, HouseIcon, Rss } from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav className="flex flex-row gap-2 font-bold text-xl bg-gray-100 p-4 text-black " >
        <Link href="/home" className="flex flex-row gap-2" ><HouseIcon /> Home</Link>
        <Link href="/" className="flex flex-row gap-2" ><Rss /> Post</Link>
        <Link href="/contact" className="flex flex-row gap-2" ><CircleUserRoundIcon /> About</Link>
      </nav>
        {children}
      </body>
    </html>
  );
}
